# Generated by Django 4.1 on 2022-09-01 21:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200, validators=[django.core.validators.EmailValidator])),
                ('password', models.CharField(max_length=100)),
                ('isConfirmed', models.BooleanField(default=False)),
                ('confirmationKey', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
